services:
  database:
    image: postgres
    ports:
      - "5001:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
  server:
    build: ./server
    ports:
    - "3000:3000"

  client:
    build: ./client
    ports:
    - "1234:1234"

volumes:
  pgdata: